CREATE DATABASE PharmaDB

-- Sử dụng Database PharmaDB (Hãy chắc chắn bạn đã tạo DB này trước)
USE PharmaDB;
GO

-- 1. Bảng Loại Sản Phẩm
CREATE TABLE LOAISP (
    MALOAI NVARCHAR(20) NOT NULL PRIMARY KEY,
    TENLOAI NVARCHAR(100)
);

-- 2. Bảng Kho
CREATE TABLE KHO (
    MAKHO NVARCHAR(20) NOT NULL PRIMARY KEY,
    TENKHO NVARCHAR(100),
    DIACHI NVARCHAR(255)
);

-- 3. Bảng Nhà Cung Cấp
CREATE TABLE NHACUNGCAP (
    MANCC NVARCHAR(20) NOT NULL PRIMARY KEY,
    TENNCC NVARCHAR(100),
    SDT NVARCHAR(20),
    EMAIL NVARCHAR(100),
    DIACHI NVARCHAR(255)
);

-- 4. Bảng Khách Hàng
CREATE TABLE KHACHHANG (
    MAKH NVARCHAR(20) NOT NULL PRIMARY KEY,
    TENKH NVARCHAR(100),
    SDT NVARCHAR(20),
    DIACHI NVARCHAR(255),
    LOAIKH NVARCHAR(50)
);

-- 5. Bảng Nhân Viên
CREATE TABLE NHANVIEN (
    MANV NVARCHAR(20) NOT NULL PRIMARY KEY,
    TENNV NVARCHAR(100),
    GIOITINH NVARCHAR(10),
    CHUCVU NVARCHAR(50),
    EMAIL NVARCHAR(100),
    CCCD NVARCHAR(20),
    SDT NVARCHAR(20),
    DIACHI NVARCHAR(255),
    NGAYSINH DATE,
    TRANGTHAI INT DEFAULT 1,
    AVATAR VARBINARY(MAX) -- Chuyển từ BLOB sang VARBINARY(MAX)
);

-- 6. Bảng Tài Khoản (Phụ thuộc NHANVIEN)
CREATE TABLE TAIKHOAN (
    MANV NVARCHAR(20) NOT NULL PRIMARY KEY,
    MATKHAU NVARCHAR(100),
    QUYENHAN NVARCHAR(50),
    TRANGTHAI INT,
    CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- 7. Bảng Sản Phẩm (Phụ thuộc LOAISP)
CREATE TABLE SANPHAM (
    MASP NVARCHAR(20) NOT NULL PRIMARY KEY,
    TENSP NVARCHAR(255),
    DVT NVARCHAR(50),
    GIABAN DECIMAL(18, 2), -- Dùng DECIMAL cho tiền tệ
    HOATCHAT NVARCHAR(255),
    NUOCSX NVARCHAR(100),
    MALOAI NVARCHAR(20),
    NHACUNGCAP NVARCHAR(100), -- Giữ nguyên cột này từ file cũ
    GHICHU NVARCHAR(MAX),
    CONSTRAINT FK_SANPHAM_LOAISP FOREIGN KEY (MALOAI) REFERENCES LOAISP(MALOAI)
);

-- 8. Bảng Lô Hàng (Phụ thuộc SANPHAM)
CREATE TABLE LOHANG (
    MALO NVARCHAR(20) NOT NULL PRIMARY KEY,
    MASP NVARCHAR(20),
    SOHIEU NVARCHAR(50),
    NSX DATE,
    HSD DATE,
    NHACUNGCAP NVARCHAR(100),
    CONSTRAINT FK_LOHANG_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

-- 9. Bảng Tồn Kho (Phụ thuộc KHO, SANPHAM, LOHANG)
CREATE TABLE TONKHO (
    MAKHO NVARCHAR(20) NOT NULL,
    MASP NVARCHAR(20) NOT NULL,
    MALO NVARCHAR(20) NOT NULL,
    SOLUONGTON INT DEFAULT 0,
    PRIMARY KEY (MAKHO, MASP, MALO),
    CONSTRAINT FK_TONKHO_KHO FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO),
    CONSTRAINT FK_TONKHO_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    CONSTRAINT FK_TONKHO_LOHANG FOREIGN KEY (MALO) REFERENCES LOHANG(MALO)
);

-- 10. Bảng Hóa Đơn Nhập (Phụ thuộc NHANVIEN, NHACUNGCAP)
CREATE TABLE HOADONNHAP (
    SOHDNHAP NVARCHAR(20) NOT NULL PRIMARY KEY,
    NGAYLAP DATETIME DEFAULT GETDATE(),
    TONGTIEN DECIMAL(18, 2),
    MANV NVARCHAR(20),
    MANCC NVARCHAR(20),
    GHICHU NVARCHAR(MAX),
    TRANGTHAI NVARCHAR(50),
    CONSTRAINT FK_HDNHAP_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_HDNHAP_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);

-- 11. Bảng Chi Tiết Hóa Đơn Nhập (Phụ thuộc HOADONNHAP, SANPHAM, LOHANG)
CREATE TABLE CTHDNHAP (
    SOHDNHAP NVARCHAR(20) NOT NULL,
    MASP NVARCHAR(20) NOT NULL,
    MALO NVARCHAR(20) NOT NULL,
    SOLUONG INT,
    DONGIANHAP DECIMAL(18, 2),
    THANHTIEN DECIMAL(18, 2),
    PRIMARY KEY (SOHDNHAP, MASP, MALO),
    CONSTRAINT FK_CTHDNHAP_HD FOREIGN KEY (SOHDNHAP) REFERENCES HOADONNHAP(SOHDNHAP),
    CONSTRAINT FK_CTHDNHAP_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    CONSTRAINT FK_CTHDNHAP_LO FOREIGN KEY (MALO) REFERENCES LOHANG(MALO)
);

-- 12. Bảng Hóa Đơn Xuất (Phụ thuộc NHANVIEN, KHACHHANG)
-- Đã thêm cột TRANGTHAI_DUYET theo yêu cầu trước đó
CREATE TABLE HOADONXUAT (
    SOHDXUAT NVARCHAR(20) NOT NULL PRIMARY KEY,
    NGAYLAP DATETIME DEFAULT GETDATE(),
    TONGTIEN DECIMAL(18, 2),
    VAT FLOAT DEFAULT 0,
    MANV NVARCHAR(20),
    MAKH NVARCHAR(20),
    TRANGTHAI NVARCHAR(50),
    TRANGTHAI_DUYET INT DEFAULT 0, -- 0: Chờ duyệt, 1: Đã duyệt
    CONSTRAINT FK_HDXUAT_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_HDXUAT_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

-- 13. Bảng Chi Tiết Hóa Đơn Xuất (Phụ thuộc HOADONXUAT, SANPHAM, LOHANG)
CREATE TABLE CTHDXUAT (
    SOHDXUAT NVARCHAR(20) NOT NULL,
    MASP NVARCHAR(20) NOT NULL,
    MALO NVARCHAR(20) NOT NULL,
    SOLUONG INT,
    DONGIABAN DECIMAL(18, 2),
    THANHTIEN DECIMAL(18, 2),
    PRIMARY KEY (SOHDXUAT, MASP, MALO),
    CONSTRAINT FK_CTHDXUAT_HD FOREIGN KEY (SOHDXUAT) REFERENCES HOADONXUAT(SOHDXUAT),
    CONSTRAINT FK_CTHDXUAT_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    CONSTRAINT FK_CTHDXUAT_LO FOREIGN KEY (MALO) REFERENCES LOHANG(MALO)
);

-- 14. Bảng Phiếu Nhập (Phụ thuộc HOADONNHAP, KHO, NHANVIEN)
CREATE TABLE PHIEUNHAP (
    MAPN NVARCHAR(20) NOT NULL PRIMARY KEY,
    SOHDNHAP NVARCHAR(20),
    MAKHO NVARCHAR(20),
    MANV NVARCHAR(20),
    NGAYNHAP DATETIME DEFAULT GETDATE(),
    GHICHU NVARCHAR(MAX),
    CONSTRAINT FK_PHIEUNHAP_HD FOREIGN KEY (SOHDNHAP) REFERENCES HOADONNHAP(SOHDNHAP),
    CONSTRAINT FK_PHIEUNHAP_KHO FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO),
    CONSTRAINT FK_PHIEUNHAP_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- 15. Bảng Phiếu Xuất (Phụ thuộc HOADONXUAT, KHO, NHANVIEN)
CREATE TABLE PHIEUXUAT (
    MAPX NVARCHAR(20) NOT NULL PRIMARY KEY,
    SOHDXUAT NVARCHAR(20),
    MAKHO NVARCHAR(20),
    MANV NVARCHAR(20),
    NGAYXUAT DATETIME DEFAULT GETDATE(),
    LYDO NVARCHAR(MAX),
    CONSTRAINT FK_PHIEUXUAT_HD FOREIGN KEY (SOHDXUAT) REFERENCES HOADONXUAT(SOHDXUAT),
    CONSTRAINT FK_PHIEUXUAT_KHO FOREIGN KEY (MAKHO) REFERENCES KHO(MAKHO),
    CONSTRAINT FK_PHIEUXUAT_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- 16. Bảng Thanh Toán (Phụ thuộc HOADONXUAT, NHANVIEN)
CREATE TABLE THANHTOAN (
    MATT NVARCHAR(20) NOT NULL PRIMARY KEY,
    SOHDXUAT NVARCHAR(20),
    SOTIEN DECIMAL(18, 2),
    NGAYTHANHTOAN DATETIME DEFAULT GETDATE(),
    PHUONGTHUC NVARCHAR(50),
    GHICHU NVARCHAR(MAX),
    MANV NVARCHAR(20),
    CONSTRAINT FK_THANHTOAN_HD FOREIGN KEY (SOHDXUAT) REFERENCES HOADONXUAT(SOHDXUAT),
    CONSTRAINT FK_THANHTOAN_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
GO

USE PharmaDB;
GO

BEGIN TRANSACTION;

-- ================================================================
-- PHẦN 1: XÓA DỮ LIỆU CŨ (THEO THỨ TỰ RÀNG BUỘC)
-- ================================================================
DELETE FROM THANHTOAN;
DELETE FROM PHIEUXUAT;
DELETE FROM CTHDXUAT;
DELETE FROM HOADONXUAT;

DELETE FROM PHIEUNHAP;
DELETE FROM CTHDNHAP;
DELETE FROM HOADONNHAP;

DELETE FROM TONKHO;
DELETE FROM LOHANG;
DELETE FROM SANPHAM;

DELETE FROM TAIKHOAN;
DELETE FROM NHANVIEN;
DELETE FROM KHACHHANG;
DELETE FROM NHACUNGCAP;
DELETE FROM KHO;
DELETE FROM LOAISP;

-- ================================================================
-- PHẦN 2: DANH MỤC CƠ BẢN
-- ================================================================

-- 1. LOẠI SẢN PHẨM
INSERT INTO LOAISP (MALOAI, TENLOAI) VALUES 
('L01', N'Thuốc giảm đau - Hạ sốt'), ('L02', N'Kháng sinh'), ('L03', N'Tim mạch'),
('L04', N'Tiêu hóa'), ('L05', N'Vitamin'), ('L06', N'Dược mỹ phẩm'),
('L07', N'Thực phẩm chức năng'), ('L08', N'Vật tư y tế');

-- 2. KHO
INSERT INTO KHO (MAKHO, TENKHO, DIACHI) VALUES 
('K01', N'Kho Tổng TP.HCM', N'Quận 1, TP.HCM'),
('K02', N'Kho Hà Nội', N'Đống Đa, Hà Nội');

-- 3. NHÀ CUNG CẤP
INSERT INTO NHACUNGCAP (MANCC, TENNCC, SDT, DIACHI) VALUES 
('NCC01', N'Dược Hậu Giang', '02923891433', N'Cần Thơ'),
('NCC02', N'Sanofi', '02838298526', N'TP.HCM'),
('NCC03', N'Traphaco', '18006612', N'Hà Nội'),
('NCC04', N'Zuellig Pharma', '02839102650', N'TP.HCM');

-- 4. KHÁCH HÀNG
INSERT INTO KHACHHANG (MAKH, TENKH, SDT, DIACHI, LOAIKH) VALUES 
('KH01', N'BV Chợ Rẫy', '02838554137', N'Q5, TP.HCM', N'Bệnh viện'),
('KH02', N'Nhà thuốc Long Châu', '18006928', N'Q3, TP.HCM', N'Nhà thuốc'),
('KH03', N'Pharmacity', '18006821', N'Q1, TP.HCM', N'Nhà thuốc'),
('KH04', N'Nguyễn Văn A', '0909123456', N'Q7, TP.HCM', N'Cá nhân');

-- 5. NHÂN VIÊN & TÀI KHOẢN
INSERT INTO NHANVIEN (MANV, TENNV, GIOITINH, CHUCVU, EMAIL, SDT, TRANGTHAI) VALUES 
('NV01', N'Huỳnh Long Bảo Khanh', N'Nam', N'Quản lý', 'admin@store.com', '0901111111', 1),
('NV02', N'Lương Phúc Khang', N'Nữ', N'Nhân viên', 'staff@store.com', '0902222222', 1),
('NV03', N'Huỳnh Gia Khang', N'Nam', N'Thủ kho', 'kho@store.com', '0903333333', 1);

INSERT INTO TAIKHOAN (MANV, MATKHAU, QUYENHAN, TRANGTHAI) VALUES 
('NV01', '123', 'Admin', 1),
('NV02', '123', 'Staff', 1),
('NV03', '123', 'Warehouse', 1);

-- ================================================================
-- PHẦN 3: HÀNG HÓA & KHO
-- ================================================================

-- 1. SẢN PHẨM
INSERT INTO SANPHAM (MASP, TENSP, DVT, GIABAN, MALOAI, NHACUNGCAP) VALUES 
('SP01', N'Panadol Extra', N'Hộp', 250000, 'L01', 'NCC01'),
('SP02', N'Augmentin 625mg', N'Hộp', 150000, 'L02', 'NCC02'),
('SP03', N'Berberin', N'Lọ', 25000, 'L04', 'NCC03'),
('SP04', N'Vitamin C 500mg', N'Lọ', 80000, 'L05', 'NCC04'),
('SP05', N'Khẩu trang Y tế', N'Hộp', 35000, 'L08', 'NCC01'),
('SP06', N'Omega 3', N'Lọ', 450000, 'L07', 'NCC04'),
('SP07', N'Kem chống nắng', N'Tuýp', 350000, 'L06', 'NCC02');

-- 2. LÔ HÀNG
INSERT INTO LOHANG (MALO, MASP, SOHIEU, NSX, HSD) VALUES 
('L01', 'SP01', 'PA001', '2023-01-01', '2026-01-01'),
('L02', 'SP02', 'AU001', '2023-02-01', '2025-02-01'),
('L03', 'SP03', 'BE001', '2023-03-01', '2026-03-01'),
('L04', 'SP04', 'VC001', '2023-04-01', '2025-04-01'),
('L05', 'SP05', 'KT001', '2024-01-01', '2027-01-01'),
('L06', 'SP06', 'OM001', '2023-12-01', '2026-12-01'),
('L07', 'SP07', 'KC001', '2023-11-01', '2026-11-01');

-- 3. TỒN KHO
INSERT INTO TONKHO (MAKHO, MASP, MALO, SOLUONGTON) VALUES 
('K01', 'SP01', 'L01', 1000), ('K01', 'SP02', 'L02', 500),
('K01', 'SP03', 'L03', 2000), ('K01', 'SP04', 'L04', 1500),
('K01', 'SP05', 'L05', 5000), ('K01', 'SP06', 'L06', 300),
('K01', 'SP07', 'L07', 400);

-- ================================================================
-- PHẦN 4: NHẬP HÀNG (HÓA ĐƠN + CHI TIẾT + PHIẾU NHẬP)
-- ================================================================

-- HDN01: Nhập kho lớn
INSERT INTO HOADONNHAP (SOHDNHAP, NGAYLAP, TONGTIEN, MANV, MANCC, TRANGTHAI) VALUES 
('HDN01', '2024-01-10', 500000000, 'NV03', 'NCC01', N'Đã thanh toán');

INSERT INTO CTHDNHAP (SOHDNHAP, MASP, MALO, SOLUONG, DONGIANHAP, THANHTIEN) VALUES 
('HDN01', 'SP01', 'L01', 1000, 150000, 150000000),
('HDN01', 'SP05', 'L05', 5000, 20000, 100000000);

-- Phiếu nhập cho HDN01
INSERT INTO PHIEUNHAP (MAPN, SOHDNHAP, MAKHO, MANV, NGAYNHAP, GHICHU) VALUES 
('PN01', 'HDN01', 'K01', 'NV03', '2024-01-10', N'Nhập đúng quy cách');

-- HDN02: Nhập bổ sung
INSERT INTO HOADONNHAP (SOHDNHAP, NGAYLAP, TONGTIEN, MANV, MANCC, TRANGTHAI) VALUES 
('HDN02', '2024-02-15', 120000000, 'NV03', 'NCC02', N'Đã thanh toán');

INSERT INTO CTHDNHAP (SOHDNHAP, MASP, MALO, SOLUONG, DONGIANHAP, THANHTIEN) VALUES 
('HDN02', 'SP02', 'L02', 500, 100000, 50000000),
('HDN02', 'SP07', 'L07', 400, 175000, 70000000);

INSERT INTO PHIEUNHAP (MAPN, SOHDNHAP, MAKHO, MANV, NGAYNHAP, GHICHU) VALUES 
('PN02', 'HDN02', 'K01', 'NV03', '2024-02-15', N'');

-- ================================================================
-- PHẦN 5: XUẤT HÀNG & THANH TOÁN & PHIẾU XUẤT
-- ================================================================

-- >>> KỊCH BẢN 1: ĐƠN HÀNG ĐÃ DUYỆT & ĐÃ THANH TOÁN & ĐÃ XUẤT KHO
-- Hóa đơn
INSERT INTO HOADONXUAT (SOHDXUAT, NGAYLAP, TONGTIEN, VAT, MANV, MAKH, TRANGTHAI, TRANGTHAI_DUYET) VALUES 
('HDX01', '2025-01-01', 5500000, 10, 'NV02', 'KH01', N'Đã thanh toán', 1);

-- Chi tiết
INSERT INTO CTHDXUAT (SOHDXUAT, MASP, MALO, SOLUONG, DONGIABAN, THANHTIEN) VALUES 
('HDX01', 'SP01', 'L01', 10, 250000, 2500000),
('HDX01', 'SP02', 'L02', 20, 150000, 3000000);

-- Phiếu xuất kho (Chỉ có khi đã duyệt)
INSERT INTO PHIEUXUAT (MAPX, SOHDXUAT, MAKHO, MANV, NGAYXUAT, LYDO) VALUES 
('PX01', 'HDX01', 'K01', 'NV03', '2025-01-01', N'Xuất bán BV Chợ Rẫy');

-- Thanh toán (Chỉ có khi đã trả tiền)
INSERT INTO THANHTOAN (MATT, SOHDXUAT, SOTIEN, NGAYTHANHTOAN, PHUONGTHUC, MANV) VALUES 
('TT01', 'HDX01', 5500000, '2025-01-01', N'Chuyển khoản', 'NV02');


-- >>> KỊCH BẢN 2: ĐƠN HÀNG CHỜ DUYỆT (ĐỂ TEST ADMIN)
-- Chưa có Phiếu xuất, Chưa có Thanh toán
INSERT INTO HOADONXUAT (SOHDXUAT, NGAYLAP, TONGTIEN, VAT, MANV, MAKH, TRANGTHAI, TRANGTHAI_DUYET) VALUES 
('HDX02', GETDATE(), 10500000, 10, 'NV02', 'KH02', N'Chờ thanh toán', 0),
('HDX03', GETDATE(), 350000, 8, 'NV02', 'KH04', N'Tiền mặt', 0);

INSERT INTO CTHDXUAT (SOHDXUAT, MASP, MALO, SOLUONG, DONGIABAN, THANHTIEN) VALUES 
('HDX02', 'SP06', 'L06', 20, 450000, 9000000), -- 20 Omega 3
('HDX02', 'SP02', 'L02', 10, 150000, 1500000),
('HDX03', 'SP05', 'L05', 10, 35000, 350000); -- 10 Khẩu trang


-- >>> KỊCH BẢN 3: ĐƠN HÀNG BỊ TỪ CHỐI
INSERT INTO HOADONXUAT (SOHDXUAT, NGAYLAP, TONGTIEN, VAT, MANV, MAKH, TRANGTHAI, TRANGTHAI_DUYET) VALUES 
('HDX04', '2025-01-20', 100000000, 10, 'NV02', 'KH04', N'Đã hủy', 2);

INSERT INTO CTHDXUAT (SOHDXUAT, MASP, MALO, SOLUONG, DONGIABAN, THANHTIEN) VALUES 
('HDX04', 'SP06', 'L06', 200, 450000, 90000000);


-- >>> KỊCH BẢN 4: ĐƠN HÀNG LỚN ĐÃ DUYỆT (CÓ THANH TOÁN 1 PHẦN)
INSERT INTO HOADONXUAT (SOHDXUAT, NGAYLAP, TONGTIEN, VAT, MANV, MAKH, TRANGTHAI, TRANGTHAI_DUYET) VALUES 
('HDX05', '2025-01-25', 25000000, 10, 'NV02', 'KH03', N'Chờ thanh toán', 1);

INSERT INTO CTHDXUAT (SOHDXUAT, MASP, MALO, SOLUONG, DONGIABAN, THANHTIEN) VALUES 
('HDX05', 'SP04', 'L04', 100, 80000, 8000000),
('HDX05', 'SP07', 'L07', 50, 350000, 17500000);

-- Phiếu xuất
INSERT INTO PHIEUXUAT (MAPX, SOHDXUAT, MAKHO, MANV, NGAYXUAT, LYDO) VALUES 
('PX05', 'HDX05', 'K01', 'NV03', '2025-01-25', N'Xuất cho Pharmacity');

-- Thanh toán đợt 1 (Đặt cọc)
INSERT INTO THANHTOAN (MATT, SOHDXUAT, SOTIEN, NGAYTHANHTOAN, PHUONGTHUC, MANV, GHICHU) VALUES 
('TT02', 'HDX05', 10000000, '2025-01-25', N'Chuyển khoản', 'NV02', N'Đặt cọc đợt 1');

COMMIT;
PRINT N'Đã thêm full dữ liệu (Danh mục, Hàng hóa, Nhập, Xuất, Phiếu kho, Thanh toán)';

USE PharmaDB;
GO

-- 1. SỬA CỘT TIỀN TỆ: DECIMAL -> FLOAT (Để khớp với double trong C#)
-- Bảng Sản phẩm
ALTER TABLE SANPHAM ALTER COLUMN GIABAN FLOAT;

-- Bảng Hóa đơn & Chi tiết
ALTER TABLE HOADONNHAP ALTER COLUMN TONGTIEN FLOAT;
ALTER TABLE HOADONXUAT ALTER COLUMN TONGTIEN FLOAT;
ALTER TABLE HOADONXUAT ALTER COLUMN VAT FLOAT;

ALTER TABLE CTHDNHAP ALTER COLUMN DONGIANHAP FLOAT;
ALTER TABLE CTHDNHAP ALTER COLUMN THANHTIEN FLOAT;

ALTER TABLE CTHDXUAT ALTER COLUMN DONGIABAN FLOAT;
ALTER TABLE CTHDXUAT ALTER COLUMN THANHTIEN FLOAT;

-- Bảng Thanh toán
ALTER TABLE THANHTOAN ALTER COLUMN SOTIEN FLOAT;

-- 2. SỬA CỘT NGÀY THÁNG: DATETIME -> NVARCHAR (Để khớp với string trong C#)
-- Lưu ý: Nếu cột có ràng buộc DEFAULT GETDATE(), ta cần xóa ràng buộc trước (nhưng để đơn giản, ta chỉ đổi kiểu dữ liệu các cột không có Default)

-- Ngày sinh nhân viên
ALTER TABLE NHANVIEN ALTER COLUMN NGAYSINH NVARCHAR(50);

-- Hạn sử dụng lô hàng
ALTER TABLE LOHANG ALTER COLUMN NSX NVARCHAR(50);
ALTER TABLE LOHANG ALTER COLUMN HSD NVARCHAR(50);

-- Chuyển cột NGAYSINH về kiểu DATE chuẩn
ALTER TABLE NHANVIEN ALTER COLUMN NGAYSINH DATE;
GO


